spring:
  datasource:
    url: jdbc:h2:file:C:/Users/navya/codepilot-ai/storage/h2db/codepilot_db;AUTO_SERVER=TRUE;DB_CLOSE_DELAY=-1;MODE=MySQL
    driver-class-name: org.h2.Driver
    username: sa
    password: 

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

  data:
    redis:
      repositories:
        enabled: false

logging:
  level:
    root: INFO
    com.codepilot: DEBUG
    org.flywaydb: INFO
